# Generated by Django 6.1 on 2026-09-08 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Company Name')),
                ('logo', models.ImageField(upload_to='clients/', verbose_name='Logo Image')),
                ('url', models.URLField(blank=True, verbose_name='Company URL')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
            ],
            options={
                'verbose_name': 'Client Logo',
                'verbose_name_plural': 'Client Logos',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.CharField(max_length=200, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Received At')),
                ('is_read', models.BooleanField(default=False, verbose_name='Read')),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=80, verbose_name='Name (EN)')),
                ('name_fr', models.CharField(blank=True, default='', max_length=80, verbose_name='Name (FR)')),
                ('name_ar', models.CharField(blank=True, default='', max_length=80, verbose_name='Name (AR)')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Project Category',
                'verbose_name_plural': 'Project Categories',
                'ordering': ['name_en'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=120, verbose_name='Title (EN)')),
                ('title_fr', models.CharField(blank=True, default='', max_length=120, verbose_name='Title (FR)')),
                ('title_ar', models.CharField(blank=True, default='', max_length=120, verbose_name='Title (AR)')),
                ('description_en', models.TextField(verbose_name='Description (EN)')),
                ('description_fr', models.TextField(blank=True, default='', verbose_name='Description (FR)')),
                ('description_ar', models.TextField(blank=True, default='', verbose_name='Description (AR)')),
                ('icon', models.CharField(choices=[('icon-web', 'Web / Globe'), ('icon-mobile', 'Mobile / Phone'), ('icon-design', 'Design / Pen'), ('icon-consulting', 'Consulting / Briefcase'), ('icon-api', 'API / Code'), ('icon-cloud', 'Cloud / DevOps'), ('icon-security', 'Security / Shield'), ('icon-data', 'Data / Database')], default='icon-web', max_length=30, verbose_name='Icon')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured on Home Page')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='getNexiro', max_length=100, verbose_name='Site Name')),
                ('tagline_en', models.CharField(default='Tech & Dev Services', max_length=200, verbose_name='Tagline (EN)')),
                ('tagline_fr', models.CharField(blank=True, default='Services Tech & Dev', max_length=200, verbose_name='Tagline (FR)')),
                ('tagline_ar', models.CharField(blank=True, default='خدمات التكنولوجيا والتطوير', max_length=200, verbose_name='Tagline (AR)')),
                ('hero_title_en', models.CharField(default='We Architect High-Velocity Digital Systems', max_length=300, verbose_name='Hero Title (EN)')),
                ('hero_title_fr', models.CharField(blank=True, default='Nous Concevons des Systèmes Numériques Haute-Performance', max_length=300, verbose_name='Hero Title (FR)')),
                ('hero_title_ar', models.CharField(blank=True, default='نصمم أنظمة رقمية عالية السرعة والأداء', max_length=300, verbose_name='Hero Title (AR)')),
                ('hero_subtitle_en', models.TextField(default='A premium software engineering agency crafting scalable web platforms, bespoke enterprise applications, and resilient digital architectures for forward-thinking organizations worldwide.', verbose_name='Hero Subtitle (EN)')),
                ('hero_subtitle_fr', models.TextField(blank=True, default="Une agence d'ingénierie logicielle haut de gamme concevant des plateformes web évolutives, des applications d'entreprise sur mesure et des architectures numériques résilientes pour les organisations visionnaires.", verbose_name='Hero Subtitle (FR)')),
                ('hero_subtitle_ar', models.TextField(blank=True, default='وكالة رائدة في هندسة البرمجيات تصمم منصات ويب قابلة للتوسع وتطبيقات مؤسسية مخصصة وبنيات تحتية رقمية مرنة للمؤسسات الطموحة في المغرب والعالم.', verbose_name='Hero Subtitle (AR)')),
                ('about_text_en', models.TextField(blank=True, default="Founded in Tangier — the vibrant city where the Atlantic meets the Mediterranean — getNexiro was born from a simple belief: world-class software doesn't need a Silicon Valley address.", verbose_name='About Us (EN)')),
                ('about_text_fr', models.TextField(blank=True, default="Fondée à Tanger — la ville vibrante où l'Atlantique rencontre la Méditerranée — getNexiro est née d'une conviction simple : les logiciels de classe mondiale n'ont pas besoin d'une adresse dans la Silicon Valley.", verbose_name='About Us (FR)')),
                ('about_text_ar', models.TextField(blank=True, default='تأسست getNexiro في طنجة — المدينة النابضة بالحياة حيث يلتقي الأطلسي بالمتوسط — من إيمان راسخ: البرمجيات العالمية لا تحتاج إلى عنوان في وادي السيليكون.', verbose_name='About Us (AR)')),
                ('mission_statement_en', models.TextField(blank=True, default='To empower enterprises with bespoke digital solutions that are not just functional, but transformative — combining technical excellence with strategic insight to create lasting competitive advantages.', verbose_name='Mission (EN)')),
                ('mission_statement_fr', models.TextField(blank=True, default="Donner aux entreprises les moyens d'agir grâce à des solutions numériques sur mesure qui ne sont pas seulement fonctionnelles, mais transformatrices — alliant excellence technique et vision stratégique.", verbose_name='Mission (FR)')),
                ('mission_statement_ar', models.TextField(blank=True, default='تمكين الشركات من خلال حلول رقمية مخصصة ليست فقط وظيفية، بل تحويلية — تجمع بين التميز الهندسي والرؤية الاستراتيجية لتحقيق ميزة تنافسية مستدامة.', verbose_name='Mission (AR)')),
                ('email', models.EmailField(default='getnexiro@gmail.com', max_length=254, verbose_name='Contact Email')),
                ('phone', models.CharField(default='+212 663 017 817', max_length=30, verbose_name='Phone Number')),
                ('address_en', models.CharField(default='Tangier 90000, Morocco', max_length=200, verbose_name='Address (EN)')),
                ('address_fr', models.CharField(blank=True, default='Tanger 90000, Maroc', max_length=200, verbose_name='Address (FR)')),
                ('address_ar', models.CharField(blank=True, default='طنجة 90000، المغرب', max_length=200, verbose_name='Address (AR)')),
                ('address_detail_en', models.CharField(default='Ibn Batouta Bureaux, Av. Youssef Ibn Tachfine', max_length=200, verbose_name='Address Detail (EN)')),
                ('address_detail_fr', models.CharField(blank=True, default='Bureaux Ibn Batouta, Av. Youssef Ibn Tachfine', max_length=200, verbose_name='Address Detail (FR)')),
                ('address_detail_ar', models.CharField(blank=True, default='مكاتب ابن بطوطة، شارع يوسف بن تاشفين', max_length=200, verbose_name='Address Detail (AR)')),
                ('business_hours_en', models.CharField(default='Mon — Fri: 9:00 AM — 6:00 PM (GMT+1)', max_length=100, verbose_name='Business Hours (EN)')),
                ('business_hours_fr', models.CharField(blank=True, default='Lun — Ven : 9h00 — 18h00 (GMT+1)', max_length=100, verbose_name='Business Hours (FR)')),
                ('business_hours_ar', models.CharField(blank=True, default='الإثنين — الجمعة: 9:00 ص — 6:00 م (GMT+1)', max_length=100, verbose_name='Business Hours (AR)')),
                ('map_embed_url', models.URLField(blank=True, default='https://www.openstreetmap.org/export/embed.html?bbox=-5.83%2C35.76%2C-5.79%2C35.79&layer=mapnik&marker=35.7796%2C-5.8030', verbose_name='Map Embed URL')),
                ('instagram_url', models.URLField(blank=True, default='https://www.instagram.com/getnexiro', verbose_name='Instagram URL')),
                ('linkedin_url', models.URLField(blank=True, default='', verbose_name='LinkedIn URL')),
                ('github_url', models.URLField(blank=True, default='https://github.com/simoderkaoui/getnexiro', verbose_name='GitHub URL')),
                ('twitter_url', models.URLField(blank=True, default='', verbose_name='Twitter / X URL')),
                ('meta_description_en', models.CharField(blank=True, default='getNexiro — Professional web development, mobile apps & software engineering agency in Tangier, Morocco.', max_length=300, verbose_name='Meta Description (EN)')),
                ('meta_description_fr', models.CharField(blank=True, default='getNexiro — Agence de développement web, applications mobiles et ingénierie logicielle à Tanger, Maroc.', max_length=300, verbose_name='Meta Description (FR)')),
                ('meta_description_ar', models.CharField(blank=True, default='getNexiro — وكالة رائدة في تطوير المواقع وتطبيقات الجوال وهندسة البرمجيات في طنجة، المغرب.', max_length=300, verbose_name='Meta Description (AR)')),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=30, verbose_name='Value')),
                ('label_en', models.CharField(max_length=120, verbose_name='Label (EN)')),
                ('label_fr', models.CharField(blank=True, default='', max_length=120, verbose_name='Label (FR)')),
                ('label_ar', models.CharField(blank=True, default='', max_length=120, verbose_name='Label (AR)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
            ],
            options={
                'verbose_name': 'Statistic',
                'verbose_name_plural': 'Statistics',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('role_en', models.CharField(max_length=120, verbose_name='Role (EN)')),
                ('role_fr', models.CharField(blank=True, default='', max_length=120, verbose_name='Role (FR)')),
                ('role_ar', models.CharField(blank=True, default='', max_length=120, verbose_name='Role (AR)')),
                ('bio_en', models.TextField(blank=True, default='', verbose_name='Bio (EN)')),
                ('bio_fr', models.TextField(blank=True, default='', verbose_name='Bio (FR)')),
                ('bio_ar', models.TextField(blank=True, default='', verbose_name='Bio (AR)')),
                ('photo', models.ImageField(upload_to='team/', verbose_name='Photo')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn URL')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_en', models.TextField(verbose_name='Quote (EN)')),
                ('quote_fr', models.TextField(blank=True, default='', verbose_name='Quote (FR)')),
                ('quote_ar', models.TextField(blank=True, default='', verbose_name='Quote (AR)')),
                ('author_name', models.CharField(max_length=100, verbose_name='Author Name')),
                ('author_role_en', models.CharField(blank=True, default='', max_length=100, verbose_name='Author Role (EN)')),
                ('author_role_fr', models.CharField(blank=True, default='', max_length=100, verbose_name='Author Role (FR)')),
                ('author_role_ar', models.CharField(blank=True, default='', max_length=100, verbose_name='Author Role (AR)')),
                ('company', models.CharField(blank=True, max_length=100, verbose_name='Company')),
                ('avatar', models.ImageField(blank=True, upload_to='testimonials/', verbose_name='Avatar')),
                ('is_featured', models.BooleanField(default=True, verbose_name='Show on Home')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=150, verbose_name='Title (EN)')),
                ('title_fr', models.CharField(blank=True, default='', max_length=150, verbose_name='Title (FR)')),
                ('title_ar', models.CharField(blank=True, default='', max_length=150, verbose_name='Title (AR)')),
                ('description_en', models.TextField(verbose_name='Description (EN)')),
                ('description_fr', models.TextField(blank=True, default='', verbose_name='Description (FR)')),
                ('description_ar', models.TextField(blank=True, default='', verbose_name='Description (AR)')),
                ('image', models.ImageField(upload_to='projects/', verbose_name='Cover Image')),
                ('client_name', models.CharField(blank=True, max_length=100, verbose_name='Client Name')),
                ('technologies', models.CharField(blank=True, max_length=300, verbose_name='Technologies')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured on Home Page')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Project Date')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.projectcategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
