# Generated by Django 6.1.1 on 2026-09-13 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_project_image_alter_teammember_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='🌍', help_text='Emoji or symbol, e.g. 🌍, 💡, 💎', max_length=30, verbose_name='Icon / Emoji')),
                ('title_en', models.CharField(max_length=120, verbose_name='Title (EN)')),
                ('title_fr', models.CharField(blank=True, default='', max_length=120, verbose_name='Title (FR)')),
                ('title_ar', models.CharField(blank=True, default='', max_length=120, verbose_name='Title (AR)')),
                ('description_en', models.TextField(verbose_name='Description (EN)')),
                ('description_fr', models.TextField(blank=True, default='', verbose_name='Description (FR)')),
                ('description_ar', models.TextField(blank=True, default='', verbose_name='Description (AR)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
            ],
            options={
                'verbose_name': 'Company Value',
                'verbose_name_plural': 'Company Values',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.CharField(default='01', help_text='e.g. 01, 02, 03, 04', max_length=10, verbose_name='Step Number')),
                ('title_en', models.CharField(max_length=120, verbose_name='Title (EN)')),
                ('title_fr', models.CharField(blank=True, default='', max_length=120, verbose_name='Title (FR)')),
                ('title_ar', models.CharField(blank=True, default='', max_length=120, verbose_name='Title (AR)')),
                ('description_en', models.TextField(verbose_name='Description (EN)')),
                ('description_fr', models.TextField(blank=True, default='', verbose_name='Description (FR)')),
                ('description_ar', models.TextField(blank=True, default='', verbose_name='Description (AR)')),
                ('tags', models.CharField(blank=True, default='Discovery, Planning', max_length=200, verbose_name='Tags (comma-separated)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
            ],
            options={
                'verbose_name': 'Process Step',
                'verbose_name_plural': 'Process Steps',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='StoreItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(default='🚀', max_length=20, verbose_name='Emoji / Icon')),
                ('title_en', models.CharField(max_length=120, verbose_name='Title (EN)')),
                ('title_fr', models.CharField(blank=True, default='', max_length=120, verbose_name='Title (FR)')),
                ('title_ar', models.CharField(blank=True, default='', max_length=120, verbose_name='Title (AR)')),
                ('description_en', models.TextField(verbose_name='Description (EN)')),
                ('description_fr', models.TextField(blank=True, default='', verbose_name='Description (FR)')),
                ('description_ar', models.TextField(blank=True, default='', verbose_name='Description (AR)')),
                ('badge_en', models.CharField(blank=True, default='COMING SOON', max_length=50, verbose_name='Badge (EN)')),
                ('badge_fr', models.CharField(blank=True, default='BIENTÔT DISPONIBLE', max_length=50, verbose_name='Badge (FR)')),
                ('badge_ar', models.CharField(blank=True, default='قريباً', max_length=50, verbose_name='Badge (AR)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Store Item',
                'verbose_name_plural': 'Store Items',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='about_image',
            field=models.ImageField(blank=True, help_text='Feature picture for About Us page (Tangier / Studio image)', null=True, upload_to='about/', verbose_name='About Page Image'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='cta_button_text_ar',
            field=models.CharField(blank=True, default='ابدأ مشروعك معنا', max_length=60, verbose_name='CTA Button (AR)'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='cta_button_text_en',
            field=models.CharField(default='Start Your Project', max_length=60, verbose_name='CTA Button (EN)'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='cta_button_text_fr',
            field=models.CharField(blank=True, default='Démarrer votre projet', max_length=60, verbose_name='CTA Button (FR)'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='cta_subtitle_ar',
            field=models.TextField(blank=True, default='احجز جلسة استشارية تقنية مع فريقنا الهندسي في طنجة.', verbose_name='CTA Subtitle (AR)'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='cta_subtitle_en',
            field=models.TextField(default='Schedule an architecture consultation with our engineering team in Tangier.', verbose_name='CTA Subtitle (EN)'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='cta_subtitle_fr',
            field=models.TextField(blank=True, default="Planifiez une consultation d'architecture avec notre équipe d'ingénierie à Tanger.", verbose_name='CTA Subtitle (FR)'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='cta_title_ar',
            field=models.CharField(blank=True, default='هل أنت مستعد لبناء مشروعك الرقمي القادم؟', max_length=200, verbose_name='CTA Title (AR)'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='cta_title_en',
            field=models.CharField(default='Ready to Architect Your Next Digital Leap?', max_length=200, verbose_name='CTA Title (EN)'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='cta_title_fr',
            field=models.CharField(blank=True, default='Prêt à concevoir votre prochain saut numérique ?', max_length=200, verbose_name='CTA Title (FR)'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_badge_ar',
            field=models.CharField(blank=True, default='استوديو برمجيات B2B • طنجة، المغرب', max_length=150, verbose_name='Hero Badge (AR)'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_badge_en',
            field=models.CharField(default='B2B Software Studio • Tangier, Morocco', max_length=150, verbose_name='Hero Badge (EN)'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_badge_fr',
            field=models.CharField(blank=True, default='Studio Logiciel B2B • Tanger, Maroc', max_length=150, verbose_name='Hero Badge (FR)'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_bg_image',
            field=models.ImageField(blank=True, null=True, upload_to='hero/', verbose_name='Hero Wallpaper / Background Image'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_bg_type',
            field=models.CharField(choices=[('default', 'Default Animated Mesh / Glow'), ('image', 'Custom Wallpaper / Image'), ('video', 'Video Background')], default='default', max_length=20, verbose_name='Hero Background Type'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_bg_video',
            field=models.FileField(blank=True, null=True, upload_to='hero/', verbose_name='Hero Background Video (MP4/WebM)'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_bg_video_url',
            field=models.URLField(blank=True, default='', verbose_name='Hero Background Video URL (Direct MP4 or external)'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_cta_primary_text_ar',
            field=models.CharField(blank=True, default='ابدأ مشروعك', max_length=60, verbose_name='Hero CTA Primary (AR)'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_cta_primary_text_en',
            field=models.CharField(default='Start a Project', max_length=60, verbose_name='Hero CTA Primary (EN)'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_cta_primary_text_fr',
            field=models.CharField(blank=True, default='Démarrer un projet', max_length=60, verbose_name='Hero CTA Primary (FR)'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_cta_secondary_text_ar',
            field=models.CharField(blank=True, default='أعمال مختارة', max_length=60, verbose_name='Hero CTA Secondary (AR)'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_cta_secondary_text_en',
            field=models.CharField(default='Selected Work', max_length=60, verbose_name='Hero CTA Secondary (EN)'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_cta_secondary_text_fr',
            field=models.CharField(blank=True, default='Nos Réalisations', max_length=60, verbose_name='Hero CTA Secondary (FR)'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='site_favicon',
            field=models.FileField(blank=True, null=True, upload_to='branding/', verbose_name='Site Favicon / Icon'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='site_logo',
            field=models.ImageField(blank=True, help_text='Website header logo (transparent PNG recommended)', null=True, upload_to='branding/', verbose_name='Site Logo'),
        ),
    ]
