# Generated by Django 6.1.1 on 2026-09-20 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_companyvalue_processstep_storeitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='challenge_ar',
            field=models.TextField(blank=True, default='', verbose_name='The Challenge (AR)'),
        ),
        migrations.AddField(
            model_name='project',
            name='challenge_en',
            field=models.TextField(blank=True, default='', verbose_name='The Challenge (EN)'),
        ),
        migrations.AddField(
            model_name='project',
            name='challenge_fr',
            field=models.TextField(blank=True, default='', verbose_name='The Challenge (FR)'),
        ),
        migrations.AddField(
            model_name='project',
            name='client_feedback_author',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Client Testimonial Author'),
        ),
        migrations.AddField(
            model_name='project',
            name='client_feedback_quote_ar',
            field=models.TextField(blank=True, default='', verbose_name='Client Testimonial Quote (AR)'),
        ),
        migrations.AddField(
            model_name='project',
            name='client_feedback_quote_en',
            field=models.TextField(blank=True, default='', verbose_name='Client Testimonial Quote (EN)'),
        ),
        migrations.AddField(
            model_name='project',
            name='client_feedback_quote_fr',
            field=models.TextField(blank=True, default='', verbose_name='Client Testimonial Quote (FR)'),
        ),
        migrations.AddField(
            model_name='project',
            name='client_feedback_role',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Client Testimonial Role'),
        ),
        migrations.AddField(
            model_name='project',
            name='duration',
            field=models.CharField(blank=True, default='3 Months', max_length=60, verbose_name='Duration'),
        ),
        migrations.AddField(
            model_name='project',
            name='github_url',
            field=models.URLField(blank=True, verbose_name='GitHub / Source URL'),
        ),
        migrations.AddField(
            model_name='project',
            name='live_url',
            field=models.URLField(blank=True, help_text='Link to live website or production application', verbose_name='Live Project URL'),
        ),
        migrations.AddField(
            model_name='project',
            name='results_ar',
            field=models.TextField(blank=True, default='', verbose_name='Results & Impact (AR)'),
        ),
        migrations.AddField(
            model_name='project',
            name='results_en',
            field=models.TextField(blank=True, default='', verbose_name='Results & Impact (EN)'),
        ),
        migrations.AddField(
            model_name='project',
            name='results_fr',
            field=models.TextField(blank=True, default='', verbose_name='Results & Impact (FR)'),
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, max_length=160, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='project',
            name='solution_ar',
            field=models.TextField(blank=True, default='', verbose_name='Architecture & Solution (AR)'),
        ),
        migrations.AddField(
            model_name='project',
            name='solution_en',
            field=models.TextField(blank=True, default='', verbose_name='Architecture & Solution (EN)'),
        ),
        migrations.AddField(
            model_name='project',
            name='solution_fr',
            field=models.TextField(blank=True, default='', verbose_name='Architecture & Solution (FR)'),
        ),
        migrations.AddField(
            model_name='project',
            name='year',
            field=models.CharField(blank=True, default='2025', max_length=20, verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description_ar',
            field=models.TextField(blank=True, default='', verbose_name='Overview (AR)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description_en',
            field=models.TextField(verbose_name='Overview (EN)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description_fr',
            field=models.TextField(blank=True, default='', verbose_name='Overview (FR)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.CharField(blank=True, max_length=300, verbose_name='Technologies (comma-separated)'),
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery/', verbose_name='Gallery Image')),
                ('caption_en', models.CharField(blank=True, default='', max_length=200, verbose_name='Caption (EN)')),
                ('caption_fr', models.CharField(blank=True, default='', max_length=200, verbose_name='Caption (FR)')),
                ('caption_ar', models.CharField(blank=True, default='', max_length=200, verbose_name='Caption (AR)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='core.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Project Gallery Image',
                'verbose_name_plural': 'Project Gallery Images',
                'ordering': ['order', 'pk'],
            },
        ),
    ]
