# Generated by Django 6.1.1 on 2026-09-20 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_project_challenge_ar_project_challenge_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='deliverables_ar',
            field=models.TextField(blank=True, default='', verbose_name='Core Deliverables (AR, newline-separated)'),
        ),
        migrations.AddField(
            model_name='service',
            name='deliverables_en',
            field=models.TextField(blank=True, default='', verbose_name='Core Deliverables (EN, newline-separated)'),
        ),
        migrations.AddField(
            model_name='service',
            name='deliverables_fr',
            field=models.TextField(blank=True, default='', verbose_name='Core Deliverables (FR, newline-separated)'),
        ),
        migrations.AddField(
            model_name='service',
            name='methodology_ar',
            field=models.TextField(blank=True, default='', verbose_name='Engineering Methodology (AR)'),
        ),
        migrations.AddField(
            model_name='service',
            name='methodology_en',
            field=models.TextField(blank=True, default='', verbose_name='Engineering Methodology (EN)'),
        ),
        migrations.AddField(
            model_name='service',
            name='methodology_fr',
            field=models.TextField(blank=True, default='', verbose_name='Engineering Methodology (FR)'),
        ),
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='service',
            name='subtitle_ar',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Tagline / Subtitle (AR)'),
        ),
        migrations.AddField(
            model_name='service',
            name='subtitle_en',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Tagline / Subtitle (EN)'),
        ),
        migrations.AddField(
            model_name='service',
            name='subtitle_fr',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Tagline / Subtitle (FR)'),
        ),
        migrations.AddField(
            model_name='service',
            name='technologies',
            field=models.CharField(blank=True, max_length=300, verbose_name='Technologies & Stacks (comma-separated)'),
        ),
        migrations.AddField(
            model_name='service',
            name='timeline',
            field=models.CharField(blank=True, default='4 — 8 Weeks', max_length=60, verbose_name='Typical Timeline'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description_ar',
            field=models.TextField(blank=True, default='', verbose_name='Overview (AR)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description_en',
            field=models.TextField(verbose_name='Overview (EN)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description_fr',
            field=models.TextField(blank=True, default='', verbose_name='Overview (FR)'),
        ),
        migrations.CreateModel(
            name='ServiceSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=150, verbose_name='Solution Title (EN)')),
                ('title_fr', models.CharField(blank=True, default='', max_length=150, verbose_name='Solution Title (FR)')),
                ('title_ar', models.CharField(blank=True, default='', max_length=150, verbose_name='Solution Title (AR)')),
                ('description_en', models.TextField(verbose_name='Solution Description (EN)')),
                ('description_fr', models.TextField(blank=True, default='', verbose_name='Solution Description (FR)')),
                ('description_ar', models.TextField(blank=True, default='', verbose_name='Solution Description (AR)')),
                ('icon_emoji', models.CharField(default='⚡', max_length=10, verbose_name='Emoji Icon')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='core.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Service Solution',
                'verbose_name_plural': 'Service Solutions',
                'ordering': ['order', 'pk'],
            },
        ),
    ]
