# Generated by Django 6.1.1 on 2026-09-20 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_service_deliverables_ar_service_deliverables_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=80, verbose_name='Name (EN)')),
                ('name_fr', models.CharField(blank=True, default='', max_length=80, verbose_name='Name (FR)')),
                ('name_ar', models.CharField(blank=True, default='', max_length=80, verbose_name='Name (AR)')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Blog Category',
                'verbose_name_plural': 'Blog Categories',
                'ordering': ['name_en'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=250, verbose_name='Title (EN)')),
                ('title_fr', models.CharField(blank=True, default='', max_length=250, verbose_name='Title (FR)')),
                ('title_ar', models.CharField(blank=True, default='', max_length=250, verbose_name='Title (AR)')),
                ('slug', models.SlugField(blank=True, max_length=280, null=True, unique=True, verbose_name='URL Slug')),
                ('excerpt_en', models.TextField(blank=True, default='', max_length=500, verbose_name='Excerpt / Summary (EN)')),
                ('excerpt_fr', models.TextField(blank=True, default='', max_length=500, verbose_name='Excerpt / Summary (FR)')),
                ('excerpt_ar', models.TextField(blank=True, default='', max_length=500, verbose_name='Excerpt / Summary (AR)')),
                ('body_en', models.TextField(verbose_name='Body (EN)')),
                ('body_fr', models.TextField(blank=True, default='', verbose_name='Body (FR)')),
                ('body_ar', models.TextField(blank=True, default='', verbose_name='Body (AR)')),
                ('meta_title_en', models.CharField(blank=True, default='', help_text='Overrides title in <title> tag. Max 70 chars.', max_length=70, verbose_name='SEO Title (EN)')),
                ('meta_title_fr', models.CharField(blank=True, default='', max_length=70, verbose_name='SEO Title (FR)')),
                ('meta_title_ar', models.CharField(blank=True, default='', max_length=70, verbose_name='SEO Title (AR)')),
                ('meta_description_en', models.CharField(blank=True, default='', help_text='Google snippet. Max 160 chars.', max_length=160, verbose_name='Meta Description (EN)')),
                ('meta_description_fr', models.CharField(blank=True, default='', max_length=160, verbose_name='Meta Description (FR)')),
                ('meta_description_ar', models.CharField(blank=True, default='', max_length=160, verbose_name='Meta Description (AR)')),
                ('meta_keywords', models.CharField(blank=True, default='', max_length=300, verbose_name='Meta Keywords (comma-separated)')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='Featured Image')),
                ('featured_image_alt', models.CharField(blank=True, default='', max_length=200, verbose_name='Image Alt Text')),
                ('author_name', models.CharField(default='getNexiro Team', max_length=100, verbose_name='Author Name')),
                ('reading_time_minutes', models.PositiveIntegerField(default=5, verbose_name='Reading Time (minutes)')),
                ('tags', models.CharField(blank=True, default='', max_length=300, verbose_name='Tags (comma-separated)')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10, verbose_name='Status')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Published At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='core.blogcategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
