# Generated by Django 6.1.1 on 2026-09-21 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_blogcategory_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='about_bg_video',
            field=models.FileField(blank=True, help_text='Custom video background for About page header', null=True, upload_to='headers/', verbose_name='About Page Video (MP4/WebM)'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='about_bg_video_url',
            field=models.URLField(blank=True, default='', help_text='Direct MP4/WebM URL for About page header', verbose_name='About Page Video URL'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='blog_bg_video',
            field=models.FileField(blank=True, help_text='Custom video background for Blog page header', null=True, upload_to='headers/', verbose_name='Blog Page Video (MP4/WebM)'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='blog_bg_video_url',
            field=models.URLField(blank=True, default='', help_text='Direct MP4/WebM URL for Blog page header', verbose_name='Blog Page Video URL'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='contact_bg_video',
            field=models.FileField(blank=True, help_text='Custom video background for Contact page header', null=True, upload_to='headers/', verbose_name='Contact Page Video (MP4/WebM)'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='contact_bg_video_url',
            field=models.URLField(blank=True, default='', help_text='Direct MP4/WebM URL for Contact page header', verbose_name='Contact Page Video URL'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='projects_bg_video',
            field=models.FileField(blank=True, help_text='Custom video background for Projects page header', null=True, upload_to='headers/', verbose_name='Projects Page Video (MP4/WebM)'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='projects_bg_video_url',
            field=models.URLField(blank=True, default='', help_text='Direct MP4/WebM URL for Projects page header', verbose_name='Projects Page Video URL'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='services_bg_video',
            field=models.FileField(blank=True, help_text='Custom video background for Services page header', null=True, upload_to='headers/', verbose_name='Services Page Video (MP4/WebM)'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='services_bg_video_url',
            field=models.URLField(blank=True, default='', help_text='Direct MP4/WebM URL for Services page header', verbose_name='Services Page Video URL'),
        ),
    ]
